@extends('frontend.partial.other')

@section('content')


<div class="container bg-light">
    <p>Last updated: December 21, 2023</p>

    <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. <br><br>
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. <br>
    </p>
    <h4>Interpretation and Definitions</h4>
    <h6>Interpretation</h6>
    <p>
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
    </p>
    <h6>Definitions</h6>
    <p>
        For the purposes of this Privacy Policy:
    </p>
    <ul>
        <li><i class="bi bi-forward-fill"></i> <strong>Account </strong>means a unique account created for You to access our Service or parts of our Service.</li>
        <li><i class="bi bi-forward-fill"></i> <strong>Company </strong>(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to HouseRent.com, H.N : 9, Road 8, uttara 10.</li>
        <li><i class="bi bi-forward-fill"></i> <strong>Cookies </strong>are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
        <li><i class="bi bi-forward-fill"></i> <strong>Country </strong>refers to: Bangladesh</li>
        <li><i class="bi bi-forward-fill"></i> <strong>Device </strong>means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
        <li><i class="bi bi-forward-fill"></i> <strong>Personal </strong>Data is any information that relates to an identified or identifiable individual.</li>
        <li><i class="bi bi-forward-fill"></i> <strong>Service </strong>refers to the Website.</li>
        <li><i class="bi bi-forward-fill"></i> <strong>Service Provider </strong>means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
        <li><i class="bi bi-forward-fill"></i> <strong>Third-party Social Media Service </strong>refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
        <li><i class="bi bi-forward-fill"></i> <strong>Usage Data </strong>refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li><i class="bi bi-forward-fill"></i> <strong>You </strong>means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
    </ul>

    <h4>Collecting and Using Your Personal Data</h4><br>
    <h5>Types of Data Collected</h5>
    <h6>Personal Data</h6>
    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>

    <ul>
        <li><i class="bi bi-forward-fill"></i> Phone number</li>
        <li><i class="bi bi-forward-fill"></i> First name and last name</li>
        <li><i class="bi bi-forward-fill"></i> Email address</li>
        <li><i class="bi bi-forward-fill"></i> Address, State, Province, ZIP/Postal code, City</li>
        <li><i class="bi bi-forward-fill"></i> Usage Data</li>
    </ul>

    <h6>Usage Data</h6>
    <p>Usage Data is collected automatically when using the Service. </p>
    <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data. </p>
    <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data. </p>
    <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>

    <h4>Information from Third-Party Social Media Services</h4>
    <p>The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:</p>
    <ul>
        <li><i class="bi bi-forward-fill"></i>Google </li>
        <li><i class="bi bi-forward-fill"></i>Facebook</li>
    </ul>
    <p>If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.</p>
    <p>You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.</p>

    <h4>Tracking Technologies and Cookies</h4>
    <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
    <ul>
        <li><i class="bi bi-forward-fill"></i> <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>

    </ul>
    <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies: Cookies: What Do They Do?.</p>

    <p>We use both Session and Persistent Cookies for the purposes set out below:</p>

    <ul>
        <li><i class="bi bi-forward-fill"></i>Necessary / Essential Cookies</li>
        <ul>
            <li>
                <p>Type: Session Cookies</p>
                <p>Administered by: Us</p>
                <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
            </li>
        </ul>

    </ul>

    <ul>
        <li><i class="bi bi-forward-fill"></i>Cookies Policy / Notice Acceptance Cookies</li>
        <ul>
            <li>
                <p>Type: Persistent Cookies</p>
                <p>Administered by: Us</p>
                <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
            </li>
        </ul>
    </ul>
    <ul>
        <li><i class="bi bi-forward-fill"></i>Functionality Cookies</li>
        <ul>
            <li>
                <p>Type: Persistent Cookies</p>
                <p>Administered by: Us</p>
                <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
            </li>
        </ul>
    </ul>

   <h5>Security of Your Personal Data</h5>
    
    <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
    
    <h5>Contact Us</h5>
    <p>If you have any questions about this Privacy Policy, You can contact us:</p>
    <ul>
        <li><i class="bi bi-forward-fill"></i>By email: trtushar35@gmail.com</li>
    </ul>
</div>

@endsection